//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UlterrariaLauncher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Steam\\steamapps\\common\\Terraria")]
        public string path {
            get {
                return ((string)(this["path"]));
            }
            set {
                this["path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfBoolean xmlns:xsi=\"http://www.w3" +
            ".org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <" +
            "boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r" +
            "\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boole" +
            "an>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</b" +
            "oolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>fals" +
            "e</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>" +
            "false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <bool" +
            "ean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <" +
            "boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r" +
            "\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boole" +
            "an>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</b" +
            "oolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>fals" +
            "e</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>" +
            "false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <bool" +
            "ean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <" +
            "boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r" +
            "\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boole" +
            "an>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</b" +
            "oolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n</ArrayOfBoolea" +
            "n>")]
        public bool[] completedAchieves {
            get {
                return ((bool[])(this["completedAchieves"]));
            }
            set {
                this["completedAchieves"] = value;
            }
        }
    }
}
